# -*- coding: utf-8 -*-
"""Perguntas1a5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uo1YFYDQhMhz49TFIhQDVmmgOhvNqqZQ

#Importação e carregamento dos dados
"""

import pandas as pd
import numpy as np

# Carregando a base de dados original via url raw do github
url_unodc = "https://raw.githubusercontent.com/Atila-dev/teste-topicos/refs/heads/main/data_cts_intentional_homicide.csv"

df_unodc = pd.read_csv(url_unodc)

"""### Limpeza e tratamento dos dados:

"""

# Criando uma cópia para preserwar o histórico
df_tratado = df_unodc.copy()

#Padronização da coluna de Idade
df_tratado['Age'] = df_tratado['Age'].astype(str).str.replace(' ', '')
df_tratado['Age'] = df_tratado['Age'].str.replace('60andolder', '60+')

#Tratando as vírgulas decimais da coluna VALUE
df_tratado['VALUE'] = pd.to_numeric(df_tratado['VALUE'].astype(str).str.replace(',', '.'), errors='coerce')

"""#Separação de Dados

Como a ONU já fez uma pré-análise dos dados, dividimos a tabela em duas separadas para que possamos fazer a nossa própria análise e, se necessário, utilizar a da ONU.
"""

# Dataset exclusivo de Países
df_paises = df_tratado[
    (~df_tratado['Indicator'].str.contains('Regional Estimate', na=False)) &
    (~df_tratado['Iso3_code'].str.startswith(('M49', 'BIG5', 'WORLD'), na=False))
].copy()

# Exportando para planilha de países
nome_paises = "dataset_homicidios_paises_tratado.csv"
df_paises.to_csv(nome_paises, index=False)

# Dataset exclusivo de Estimativas Regionais da ONU
df_onu = df_tratado[
    (df_tratado['Indicator'].str.contains('Regional Estimate', na=False)) |
    (df_tratado['Iso3_code'].str.startswith(('M49', 'BIG5', 'WORLD'), na=False))
].copy()

# Exportando para planilha de regiões
nome_onu = "dataset_homicidios_regioes_onu_tratado.csv"
df_onu.to_csv(nome_onu, index=False)

"""#Visões dos dados"""

display(df_paises.shape)
display(df_onu.shape)

display(df_paises.describe())
print("\n")
display(df_onu.describe())

print(f"Valores Nulos: {df_paises.isnull().sum().sum()}")
print(f"Linhas Duplicadas: {df_paises.duplicated().sum()}")
print(f"Valores Nulos (ONU): {df_onu.isnull().sum().sum()}")
print(f"Linhas Duplicadas (ONU): {df_onu.duplicated().sum()}")

"""# Análise Exploratória

##1. Quais países apresentaram os 10 maiores índices de homicídios nos últimos 5 anos?

* Utilizou-se o DataFrame `df_paises`, pois a requisição especifica entidades nacionais, excluindo os dados macro da ONU.

* A seleção de `Rate per 100,000 population` foi aplicada. O uso de números absolutos (`Counts`) resultaria em um viés populacional, onde países com maior número de habitantes apareceriam no topo do ranking independentemente da severidade real do índice de criminalidade.

* O método `.mean()` foi escolhido para calcular a média do índice ao longo dos 5 anos, estabelecendo um valor representativo do período solicitado em vez de selecionar um pico isolado de um único ano.
"""

# Definição do período de análise
anos_alvo = [2018, 2019, 2020, 2021, 2022]

# Filtragem
df_taxa = df_paises[
    (df_paises['Year'].isin(anos_alvo)) &
    (df_paises['Indicator'] == 'Victims of intentional homicide') &
    (df_paises['Unit of measurement'] == 'Rate per 100,000 population') &
    (df_paises['Sex'] == 'Total') &
    (df_paises['Age'] == 'Total') &
    (df_paises['Dimension'] == 'Total') &
    (df_paises['Category'] == 'Total')
].copy()

# Agrupamento por país e cálculo da média da taxa no período de 5 anos
taxa_media_paises = df_taxa.groupby('Country')['VALUE'].mean().reset_index()

# Ordenação descendente e seleção dos 10 primeiros
top_10_paises = taxa_media_paises.sort_values(by='VALUE', ascending=False).head(10)

# Renomeação da coluna para adequação de nomenclatura
top_10_paises = top_10_paises.rename(columns={'VALUE': 'Taxa Média (por 100 mil hab.)'})

# Exibição da tabela final
display(top_10_paises.reset_index(drop=True))

"""##2. Quais países apresentam os 10 maiores índices de homicídios de mulheres em 2022?

* O uso da taxa por 100.000 habitantes foi mantido. Utilizar contagens absolutas (`Counts`) em recortes de gênero introduz distorções severas, pois países com grandes populações femininas liderariam a lista em números absolutos, ocultando a real proporção do risco letal no país.
"""

# Filtragem
df_mulheres_2022 = df_paises[
    (df_paises['Year'] == 2022) &
    (df_paises['Sex'] == 'Female') &
    (df_paises['Indicator'] == 'Victims of intentional homicide') &
    (df_paises['Unit of measurement'] == 'Rate per 100,000 population') &
    (df_paises['Age'] == 'Total') &
    (df_paises['Dimension'] == 'Total') &
    (df_paises['Category'] == 'Total')
].copy()

# Ordenação
top_10_mulheres_2022 = df_mulheres_2022.sort_values(by='VALUE', ascending=False).head(10)

# Isolamento das colunas de interesse e renomeação para apresentação
top_10_mulheres_2022 = top_10_mulheres_2022[['Country', 'VALUE']]
top_10_mulheres_2022 = top_10_mulheres_2022.rename(columns={'VALUE': 'Taxa de Homicídios (Mulheres por 100 mil hab.)'})

# Exibição da tabela resultante
display(top_10_mulheres_2022.reset_index(drop=True))

"""* Ao analisar dados de homicídios filtrados por gênero, avaliar apenas a taxa isolada pode omitir o contexto da dinâmica criminal do país. Um tratamento analítico adicional de alto valor é calcular a **proporção de vítimas femininas em relação ao total de vítimas** nesses mesmos 10 países. Isso permite identificar se o alto índice reflete uma criminalidade geral elevada no país ou um problema de letalidade desproporcionalmente focado em mulheres.

* Para realizar esta análise de proporção, é mandatório utilizar a unidade `Counts` (números absolutos), pois taxas não podem ser somadas ou divididas diretamente com precisão demográfica.
"""

# Obtenção da lista dos 10 países identificados anteriormente
paises_alvo = top_10_mulheres_2022['Country'].tolist()

# Filtro base para valores absolutos (Counts) em 2022 para os países do Top 10
df_counts_2022 = df_paises[
    (df_paises['Country'].isin(paises_alvo)) &
    (df_paises['Year'] == 2022) &
    (df_paises['Indicator'] == 'Victims of intentional homicide') &
    (df_paises['Unit of measurement'] == 'Counts') &
    (df_paises['Age'] == 'Total') &
    (df_paises['Dimension'] == 'Total') &
    (df_paises['Category'] == 'Total')
]

# Extração dos totais femininos
df_fem_counts = df_counts_2022[df_counts_2022['Sex'] == 'Female'][['Country', 'VALUE']]
df_fem_counts = df_fem_counts.rename(columns={'VALUE': 'Vítimas Mulheres'})

# Extração dos totais gerais
df_total_counts = df_counts_2022[df_counts_2022['Sex'] == 'Total'][['Country', 'VALUE']]
df_total_counts = df_total_counts.rename(columns={'VALUE': 'Total de Vítimas'})

# Mesclagem dos dados e cálculo percentual
df_proporcao = pd.merge(df_fem_counts, df_total_counts, on='Country')
df_proporcao['Proporção Feminina (%)'] = (df_proporcao['Vítimas Mulheres'] / df_proporcao['Total de Vítimas']) * 100

# Ordenação pela proporção e exibição
df_proporcao = df_proporcao.sort_values(by='Proporção Feminina (%)', ascending=False)
display(df_proporcao.reset_index(drop=True))

"""##3. Quais as regiões com mais homicídios?

* A escolha por `Counts` (valores absolutos) foi feita porque a pergunta busca saber onde há "mais homicídios" fisicamente, o que requer a contagem direta de vítimas. A taxa por 100 mil habitantes indicaria o risco letal proporcional, não o volume total.

* Utilizou-se a função `.groupby('Region')` no DataFrame `df_paises`. Isso permite somar os dados de todos os países que compõem cada continente/região de forma controlada.
"""

# Filtragem
df_regioes = df_paises[
    (df_paises['Indicator'] == 'Victims of intentional homicide') &
    (df_paises['Unit of measurement'] == 'Counts') &
    (df_paises['Sex'] == 'Total') &
    (df_paises['Age'] == 'Total') &
    (df_paises['Dimension'] == 'Total') &
    (df_paises['Category'] == 'Total')
].copy()

# Agrupamento pela coluna 'Region' e soma de todos os registros históricos
ranking_regioes = df_regioes.groupby('Region')['VALUE'].sum().reset_index()

# Ordenação
ranking_regioes = ranking_regioes.sort_values(by='VALUE', ascending=False)

# Renomeação da coluna para clareza dos dados apresentados
ranking_regioes = ranking_regioes.rename(columns={'VALUE': 'Total de Homicídios'})

# Exibição da tabela
display(ranking_regioes.reset_index(drop=True))

"""##4. Quais países com menor número de homicídios em cada sub-região?

* O método `.groupby(['Subregion', 'Country'])` unifica os dados de todos os anos para cada país.

* A função `.idxmin()` foi selecionada por ser a forma mais eficiente no Pandas para retornar o índice da linha que contém o valor mínimo dentro de um grupo específico. Após obter os índices, a função `.loc[]` resgata as linhas completas, mantendo o nome do país associado ao valor mínimo.
"""

# Filtragem
df_subregiao = df_paises[
    (df_paises['Indicator'] == 'Victims of intentional homicide') &
    (df_paises['Unit of measurement'] == 'Counts') &
    (df_paises['Sex'] == 'Total') &
    (df_paises['Age'] == 'Total') &
    (df_paises['Dimension'] == 'Total') &
    (df_paises['Category'] == 'Total')
].copy()

# Agrupamento por Sub-região e País para somar o total histórico de homicídios
total_pais_subregiao = df_subregiao.groupby(['Subregion', 'Country'])['VALUE'].sum().reset_index()

# Obtenção dos índices com o valor mínimo de homicídios em cada sub-região
indices_menores = total_pais_subregiao.groupby('Subregion')['VALUE'].idxmin()

# Filtragem do dataframe original utilizando os índices encontrados
paises_menores_homicidios = total_pais_subregiao.loc[indices_menores]

# Ordenação por sub-região e renomeação da coluna de valores
paises_menores_homicidios = paises_menores_homicidios.sort_values(by=['Subregion'])
paises_menores_homicidios = paises_menores_homicidios.rename(columns={'VALUE': 'Total de Homicídios'})

# Exibição da tabela resultante
display(paises_menores_homicidios.reset_index(drop=True))

"""* Avaliar a soma total de anos não especificados gera um problema estatístico: por exemplo, um país que forneceu dados para a ONU durante apenas 1 ano poderá registrar um total acumulado menor do que um microestado seguro que forneceu dados consistentemente por 20 anos.

* Para realizar uma comparação estatística justa entre os países de cada sub-região, a métrica apropriada é a **Média Anual de Homicídios**, em vez da soma bruta do período.
"""

# Agrupamento para encontrar a média anual de homicídios por país
media_anual_pais = df_subregiao.groupby(['Subregion', 'Country'])['VALUE'].mean().reset_index()

# Obtenção dos índices com a menor média anual dentro de cada sub-região
indices_menores_medias = media_anual_pais.groupby('Subregion')['VALUE'].idxmin()

# Filtragem das linhas correspondentes
menores_medias_subregiao = media_anual_pais.loc[indices_menores_medias]

# Ordenação e formatação final
menores_medias_subregiao = menores_medias_subregiao.sort_values(by='Subregion')
menores_medias_subregiao = menores_medias_subregiao.rename(columns={'VALUE': 'Média Anual de Homicídios'})

# Exibição do resultado padronizado
display(menores_medias_subregiao.reset_index(drop=True))

"""##5. Quais países com menor número de mortes de mulheres?

* O filtro `Sex == 'Female'` restringe a busca ao sexo feminino. As demais variáveis (`Age, Dimension, Category`) foram fixadas em `Total` para garantir a integridade da soma, impedindo a contagem duplicada de subcategorias metodológicas.
"""

# Filtragem
df_menor_mulheres = df_paises[
    (df_paises['Sex'] == 'Female') &
    (df_paises['Indicator'] == 'Victims of intentional homicide') &
    (df_paises['Unit of measurement'] == 'Counts') &
    (df_paises['Age'] == 'Total') &
    (df_paises['Dimension'] == 'Total') &
    (df_paises['Category'] == 'Total')
].copy()

# Agrupamento por país e soma de todos os registros históricos disponíveis
total_mulheres_pais = df_menor_mulheres.groupby('Country')['VALUE'].sum().reset_index()

# Ordenação
top_10_menores_mulheres = total_mulheres_pais.sort_values(by='VALUE', ascending=True)

# Renomeação
top_10_menores_mulheres = top_10_menores_mulheres.rename(columns={'VALUE': 'Total de Vítimas Mulheres'})

# Exibição da tabela
display(top_10_menores_mulheres.reset_index(drop=True))

"""* A utilização de números absolutos na busca por menores índices criminais gera um viés demográfico severo. Microestados invariavelmente exibirão os menores números absolutos devido à sua população reduzida, enquanto nações que falharam em reportar dados para a ONU na maioria dos anos apresentarão somas acumuladas artificialmente baixas.

* O tratamento adequado para estabelecer uma comparação proporcional e justa sobre a segurança da população feminina entre os países exige o uso da taxa populacional e a extração da média anual.
"""

# Filtragem utilizando a taxa proporcional (Rate) em vez de valores absolutos
df_taxa_mulheres = df_paises[
    (df_paises['Sex'] == 'Female') &
    (df_paises['Indicator'] == 'Victims of intentional homicide') &
    (df_paises['Unit of measurement'] == 'Rate per 100,000 population') &
    (df_paises['Age'] == 'Total') &
    (df_paises['Dimension'] == 'Total') &
    (df_paises['Category'] == 'Total')
].copy()

# Cálculo da média histórica da taxa para nivelar anos não reportados
media_taxa_mulheres = df_taxa_mulheres.groupby('Country')['VALUE'].mean().reset_index()

# Ordenação
top_10_menores_taxas_mulheres = media_taxa_mulheres.sort_values(by='VALUE', ascending=True)

# Renomeação
top_10_menores_taxas_mulheres = top_10_menores_taxas_mulheres.rename(columns={'VALUE': 'Taxa Média de Homicídios (Mulheres por 100 mil hab.)'})

# Exibição da tabela tratada
display(top_10_menores_taxas_mulheres.reset_index(drop=True))