# -*- coding: utf-8 -*-
"""Topicos_Regr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r2uWPups1EFy5Hs6DBTDmpBqFxe1NIXL

# Projeto: Global Homicide Trends and Regression Predictive Analysis
## Parte 4: Análise de Regressão
**Responsável:** Lucas
"""

import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Carregando a base de dados
df = pd.read_csv('/content/drive/MyDrive/dataset_homicidios_preparado.csv')
print("Dados carregados com sucesso! Linhas e colunas:", df.shape)

"""####Definindo País"""

# Definir o país alvo
pais_alvo = 'Brazil'

# Filtrando o período
df_filtrado = df[
    (df['Country'] == pais_alvo) &
    (df['Sex'] == 'Total') &
    (df['Year'] >= 2013) &
    (df['Year'] <= 2022)
].copy()

"""#### Tratamento dos Dados"""

# Agrupar por ano e extrair o MÁXIMO
df_agrupado = df_filtrado.groupby('Year')['VALUE'].max().reset_index()

# Tratar o ano que tem valor 0
df_agrupado['VALUE'] = df_agrupado['VALUE'].replace(0, np.nan)
df_agrupado['VALUE'] = df_agrupado['VALUE'].interpolate()

"""#### Modelagem de Previsão"""

# Definindo Entradas e Saídas
X = df_agrupado[['Year']]
y = df_agrupado['VALUE']

# Regressão Linear Simples direta nos valores reais
modelo_final = LinearRegression()
modelo_final.fit(X, y)

# Calculando o Erro no Treinamento
previsoes_treino = modelo_final.predict(X)
mse_final = mean_squared_error(y, previsoes_treino)

print(f"TREINAMENTO CONCLUÍDO PARA: {pais_alvo} (Período: 2013-2022)")
print(f"Erro Quadrático Médio (MSE) no Treino: {mse_final:.0f}\n")

"""#### Gerando Previsões Futuras"""

anos_futuros = [2023, 2024, 2025, 2026]
dados_futuros = pd.DataFrame({'Year': anos_futuros})

# Realizando a predição futura
previsoes_futuras = modelo_final.predict(dados_futuros)

print("PREVISÕES DE HOMICÍDIOS PARA O FUTURO:")
for ano, taxa in zip(anos_futuros, previsoes_futuras):
    # Formatação limpa na casa dos milhares
    print(f"   Ano {ano}: {taxa:.0f}")